language: node
addons:
  sonarcloud:
    organization: "marmer-github"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
after_script:
  - sonar-scanner
